"""add user language preference

Revision ID: 66b1e79055b5
Revises: aca145102282
Create Date: 2026-09-01 07:00:32.627302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b1e79055b5'
down_revision: Union[str, None] = 'aca145102282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: adding a NOT NULL
    # column to a table that already has rows needs a server_default so
    # Postgres can backfill existing rows; autogenerate doesn't add one on
    # its own and this would otherwise fail on any non-empty users table. ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'language', sa.String(length=10), nullable=False, server_default='en'
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
