"""add admin_action_logs table

Revision ID: aca145102282
Revises: 074df6640eae
Create Date: 2026-09-01 06:28:29.415058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca145102282'
down_revision: Union[str, None] = '074df6640eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_action_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_logs_admin_telegram_id'), ['admin_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_logs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_action_logs_admin_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_admin_action_logs_action'))

    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
